### ISSUE TITLE
Add link to google chrome , Edge 

### ISSUE THREAD

**Issue by PumpkinManiac** [anand-3399/Hactoberfest-Windows11#10]
Add more icons like netflix and redirect them to their pages

**Comment by anand-3399** [comment]
> Add more icons like netflix and redirect them to their pages

This is not required @PumpkinManiac 
If you want to contribute then you can make a Window of the Apps like Google Chrome Window, Edge Window or else any App Window. Just like in Windows OS, we can open Applications.
Hope you understand.

**Comment by anand-3399** [comment]
> > Add more icons like netflix and redirect them to their pages
> 
> This is not required @PumpkinManiac If you want to contribute then you can make a Window of the Apps like Google Chrome Window, Edge Window or else any App Window. Just like in Windows OS, we can open Applications. Hope you understand.

If you want to contribute on this issue then you can definitely open a new issue regarding this.
