### ISSUE TITLE
Date & Time Menu

### ISSUE THREAD

**Issue by dilipsuthar1999** [anand-3399/Hactoberfest-Windows11#11]
- Date & Time menu will pop up when click on date & time at bottom of corner (Taskbar)
- Make Responsive design

**Comment by dilipsuthar1999** [comment]
Can, you assign this task to me

**Comment by anand-3399** [comment]
> * Date & Time menu will pop up when click on date & time at bottom of corner (Taskbar)
> * Make Responsive design

#### Can you show me tentative design of your Goal?
This may not be final design but a tentative design of your feature.

**Comment by dilipsuthar1999** [comment]
![win11_D T](https://user-images.githubusercontent.com/61174714/194931449-bd0d18a8-c94e-449f-b865-6a1c32647095.jpg)

**Comment by anand-3399** [comment]
> ![win11_D T](https://user-images.githubusercontent.com/61174714/194931449-bd0d18a8-c94e-449f-b865-6a1c32647095.jpg)

Looks Awesome!!
I have assigned you @dilipsuthar1999  this issue. Please star this repository and fork with your pull request so that I can merge your pull request. 
Keep Coding!!!

**Comment by dilipsuthar1999** [comment]
Thanks, I started on this. Will update you soon :)

**Comment by anand-3399** [comment]
Completed in #14 by @dilipsuthar1999
