### ISSUE TITLE
UI Design Fix

### ISSUE THREAD

**Issue by dilipsuthar1999** [anand-3399/Hactoberfest-Windows11#16]
1. Try to fix color in website as you can see in #11 
2. Background Video of win11, remove loop and add background color. Make looks like win11 background.

**Comment by anand-3399** [comment]
**Good Issue!**
1. But  If you are fixing the color in https://github.com/anand-3399/Hactoberfest-Windows11/issues/11 try not to use experimental or different colors.
2. Make the images or fonts accurate like upward and downward arrow.
3. And if you are adding background color to the Win11 then you should make this color look accurate and exact.
4. If all these criteria is met You are good to go

 ![win11_D T](https://user-images.githubusercontent.com/61174714/194931449-bd0d18a8-c94e-449f-b865-6a1c32647095.jpg)

**Comment by dilipsuthar1999** [comment]
@anand-3399, I am adding color means background color in widget menu, search menu, start menu, taskbar looks like date-time menu.
