### ISSUE TITLE
working of apps 

### ISSUE THREAD

**Issue by MAVERICK-VF142** [anand-3399/Hactoberfest-Windows11#7]
such a on clicking on likedin it will direct us to linkedin page and etc

**Comment by anand-3399** [comment]
This is not required.
If you want to contribute then you can make a Window of the Apps like Google Chrome Window, Edge Window or else any App Window. Just like in Windows OS, we can open Applications.
Hope you understand.

**Comment by anand-3399** [comment]
If you want to contribute on this issue then you can definitely open a new issue regarding this.
