### ISSUE TITLE
working of all apps button in start menu and addition of vs code icon in desktop

### ISSUE THREAD

**Issue by MAVERICK-VF142** [anand-3399/Hactoberfest-Windows11#8]

**Comment by anand-3399** [comment]
Say me the tentative description or approach of your idea!

**Comment by MAVERICK-VF142** [comment]
like if we press the all apps button it will show all apps in start menu just as in windows 11

**Comment by anand-3399** [comment]
Okk Cool!!!

**Comment by anand-3399** [comment]
I have assigned you @MAVERICK-VF142  this issue. Please star this repository and fork with your pull request so that I can merge your pull request. Keep Coding!!!

**Comment by MAVERICK-VF142** [comment]
can you tell me how to delete the animation of fullscreen

**Comment by anand-3399** [comment]
We can discuss this in discussion section!
